# Generated by Django 5.2.3 on 2025-06-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoChecagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_minutos', models.PositiveIntegerField()),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='TunelDePreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.ativo')),
            ],
        ),
    ]
