# Generated by Django 5.2.3 on 2025-06-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuneldepreco',
            name='user',
        ),
    ]
