# Generated by Django 5.2.3 on 2025-06-18 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_remove_tuneldepreco_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='ativo',
            unique_together={('user', 'ticker')},
        ),
    ]
