# Generated by Django 5.2.3 on 2025-06-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_ativo_ticker_alter_ativo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='intervalo_checagem',
            field=models.PositiveIntegerField(choices=[(1, '1 minuto'), (5, '5 minutos'), (15, '15 minutos'), (30, '30 minutos'), (60, '1 hora')], default=5, verbose_name='Intervalo de Checagem (minutos)'),
        ),
    ]
