# Generated by Django 5.2.3 on 2025-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_ativo_intervalo_checagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='estado',
            field=models.IntegerField(default=0, verbose_name='Estado do Ativo (0: neutro, -1: abaixo do túnel, 1: acima do túnel)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='ultima_checagem',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Checagem'),
        ),
    ]
