# Generated by Django 5.2.3 on 2025-06-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_ativo_estado_ativo_ultima_checagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoChecagem',
        ),
    ]
